src/components/DcChartEditor/editor-panel/index.scss
src/components/DcChartEditor/switch-chart-type/index.tsx
src/types/index.d.ts

feat: add Tooltip to chart icon

---

.prettierrc.js
src/components/DcBoard/common/grid-items.tsx
src/components/DcBoard/common/utils/index.ts
src/components/DcBoard/grid.tsx
src/components/DcBoard/header.tsx
src/components/DcBoard/index.tsx
src/components/DcBoard/pure-board.tsx
src/components/DcBoard/pure-grid.tsx
src/components/DcChartEditor/data-config/dice-form/data-loader.ts
src/components/DcChartEditor/data-config/dice-form/index.tsx
src/components/DcChartEditor/data-config/index.tsx
src/components/DcChartEditor/index.tsx
src/components/DcChartEditor/pick-chart-modal/index.tsx
src/components/DcChartEditor/switch-chart-type/index.tsx
src/components/DcCharts/chart-funnel/configurator.tsx
src/components/DcCharts/chart-funnel/option.ts
src/components/DcCharts/chart-line/configurator.tsx
src/components/DcCharts/chart-line/option.ts
src/components/DcCharts/chart-map/index.tsx
src/components/DcCharts/chart-map/option.ts
src/components/DcCharts/chart-pie/configurator.tsx
src/components/DcCharts/chart-pie/option.ts
src/components/DcCharts/chart-table/configurator.tsx
src/components/DcCharts/common/common-configurator.tsx
src/components/DcCharts/common/custom-option.ts
src/components/DcCharts/index.tsx
src/components/DcContainer/index.tsx
src/config/index.ts
src/services/chart-editor.ts
src/stores/chart-editor.ts

For 'export default DC',  refactor the import way of DC

refactor: refactor the import way of DC

---

src/components/DcChartEditor/data-config/dice-form/index.tsx

feat: add round_float to latest value

---

src/components/DcChartEditor/data-config/dice-form/data-loader.ts
src/components/DcCharts/chart-table/index.tsx

add origin data into table record

add origin data to datasource

---

src/components/DcChartEditor/data-config/dice-form/index.tsx

fix when switching types, the data is not up to date

fix: switch other type after switching map type

---

src/components/DcBoard/grid.tsx
src/components/DcBoard/header.tsx
src/components/DcBoard/pure-board.tsx
src/components/DcBoard/pure-header.tsx
src/components/DcChartEditor/data-config/dice-form/constants.ts
src/components/DcChartEditor/data-config/dice-form/data-loader.ts
src/components/DcChartEditor/data-config/dice-form/dimensions-configurator/create-alias-modal.tsx
src/components/DcChartEditor/data-config/dice-form/dimensions-configurator/create-expr-modal.tsx
src/components/DcChartEditor/data-config/dice-form/dimensions-configurator/create-filter-modal.tsx
src/components/DcChartEditor/data-config/dice-form/dimensions-configurator/create-time-modal.tsx
src/components/DcChartEditor/data-config/dice-form/dimensions-configurator/dimension-configs.tsx
src/components/DcChartEditor/data-config/dice-form/dimensions-configurator/index.tsx
src/components/DcChartEditor/data-config/dice-form/index.tsx
src/components/DcChartEditor/editor-panel/index.tsx
src/components/DcChartEditor/switch-chart-type/index.tsx
src/components/DcCharts/chart-funnel/configurator.tsx
src/components/DcCharts/chart-line/configurator.tsx
src/components/DcCharts/chart-map/configurator.tsx
src/components/DcCharts/chart-metric/configurator.tsx
src/components/DcCharts/chart-pie/configurator.tsx
src/components/DcCharts/chart-table/configurator.tsx
src/components/DcCharts/common/common-configurator.tsx
src/components/DcContainer/options.tsx
src/components/DcGlobalFilters/config-modal.tsx
src/stores/dash-board.ts
src/utils/comp.ts

Fix the problem that switching Chinese and English

Hotfix: Chinese and English switching

---

src/constants/index.ts
src/stores/chart-editor.ts

Fix that i18n the default title of chart

fix: i18n the default title of chart

---

src/components/DcChartEditor/data-config/dice-form/data-loader.ts
src/components/DcChartEditor/data-config/dice-form/types/index.d.ts
src/components/DcCharts/chart-table/index.tsx

fix: cell of table supports ellipsis

---

src/components/DcBoard/header.tsx

update button type from default to text

style: update button to type of text

---

package-lock.json
package.json

chore: upgrade cube state to v1.5.3

---

src/components/DcChartEditor/data-config/dice-form/dimensions-configurator/create-filter-modal.tsx

fix: fix the input width in modal

---

src/common/utils/copy.tsx
src/components/DcChartEditor/data-config/dice-form/data-loader.ts
src/components/DcChartEditor/data-config/dice-form/types/index.d.ts
src/components/DcCharts/chart-table/index.tsx
src/constants/index.ts

1. add copy function to table cell
2. fix Safari version under v13.1 which can't support replaceAll
Fixes #

feat: add copy table cell

---

src/common/utils/agent.js
src/components/DcCharts/chart-funnel/option.ts
src/components/DcCharts/chart-line/option.ts
src/components/DcCharts/chart-map/option.ts
src/components/DcCharts/chart-pie/option.ts
src/stores/dash-board.ts

1. set language to request header 
2. support API cover options to config charts
Fixes #

fix: add language to head request and accept options to config chart

---

src/components/DcChartEditor/data-config/dice-form/data-loader.ts
src/components/DcCharts/chart-line/option.ts

line type, multiple y-axes
Fixes #

fix: multiple y axes

---

src/components/DcCharts/chart-line/option.ts

add param to display complete tooltip
Fixes #

feat: add param to display complete tooltip

---

CHANGELOG.md
package.json

upgrade changeLog and package.json
Fixes #

chore: upgrade to v1.0.42

---

src/components/DcContainer/index.tsx
src/services/chart-editor.ts

check isArray in request body
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D

fix: check isArray in request body

---

src/common/utils/replace-variable.ts

fix zero will transform to undefined in the dashboard
Fixes #

fix: fix zero will transform to undefined in dashboard

---

src/common/form-builder/fields.tsx
src/components/DcChartEditor/data-config/dice-form/index.tsx
src/components/DcChartEditor/editor-panel/index.tsx
src/stores/chart-editor.ts

checking required fields before submitting
checking required fields before submitting
Fixes #

Fix: submit dashboard editor check

---

CHANGELOG.md
package.json

upgrade changeLog to v2.0.0
upgrade changeLog to v2.0.0
Fixes #

docs: upgrade changeLog to v2.0.0

---

src/common/utils/agent.ts

filter query meaningful value
Fixes #
[【服务分析】使用ES存储trace/error和log数据后，服务概览中有图表显示有问题](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D)

fix: filter query meaningful value

---

CHANGELOG.md
package.json

update changeLog and package.json to v2.0.1
Fixes #

chore: update changeLog and package.json

---

src/components/DcBoard/index.tsx
src/components/DcBoard/pure-board.tsx
src/utils/locale.ts
src/utils/locale.tsx

i18n impact erda-ui error, remove ConfigProvider from dashboard when is production env
Fixes #

fix: i18n impact erda-ui error

---

CHANGELOG.md
package.json

update changeLog and package.json
Fixes #

docs: update changeLog and package.json

---

src/components/DcChartEditor/editor-panel/index.tsx
src/components/DcContainer/index.tsx
src/constants/index.ts
src/stores/chart-editor.ts

1. display no mask which reminds user get data failed when didn't complete required fields
2. line chart selected by default when add chart
Fixes #

fix: display no mask when did not complete required fields

---

CHANGELOG.md
package.json

update changeLog and package.json
Fixes #

fix: update changeLog and package.json

---

src/components/DcBoard/common/grid-items.tsx
src/components/DcBoard/common/utils/index.ts
src/components/DcBoard/header.tsx
src/components/DcBoard/index.tsx
src/components/DcBoard/pure-board.tsx
src/components/DcBoard/pure-grid.tsx
src/components/DcChartEditor/data-config/index.tsx
src/components/DcChartEditor/pick-chart-modal/index.tsx
src/components/DcChartEditor/switch-chart-type/index.tsx
src/components/DcCharts/chart-funnel/configurator.tsx
src/components/DcCharts/chart-funnel/option.ts
src/components/DcCharts/chart-line/configurator.tsx
src/components/DcCharts/chart-line/option.ts
src/components/DcCharts/chart-map/index.tsx
src/components/DcCharts/chart-map/option.ts
src/components/DcCharts/chart-pie/configurator.tsx
src/components/DcCharts/chart-pie/option.ts
src/components/DcCharts/chart-table/configurator.tsx
src/components/DcCharts/common/common-configurator.tsx
src/components/DcCharts/common/custom-option.ts
src/components/DcCharts/index.tsx
src/components/DcContainer/index.tsx
src/services/chart-editor.ts
src/stores/chart-editor.ts
src/utils/locale.tsx

feat: remove import DC

---

CHANGELOG.md
package.json

update changeLog to v2.0.4
Fixes #

docs: update changeLog to v2.0.4

---

CHANGELOG.md
package-lock.json
package.json

fix: lock minor version

---

CHANGELOG.md
package.json
src/common/form-builder/fields.tsx
src/constants/index.ts

fix  i18n in validating required fields
i18n in validating required fields
Fixes #
[【集成环境】【国际化】自定义大盘，新增/编辑页面，字段为空时，提示语没有翻译](https://erda.cloud/erda/dop/projects/387/issues/all?id=277529&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA3MjMiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)

fix: i18n in validating required fields

---

CHANGELOG.md
src/components/DcCharts/chart-funnel/option.ts
src/components/DcCharts/chart-line/option.ts
src/components/DcCharts/chart-metric/index.tsx
src/components/DcCharts/chart-pie/option.ts
src/components/DcCharts/chart-table/index.tsx

fix: complete i18n in charts
Fixes #
complete i18n in charts

fix: complete i18n in charts

---

CHANGELOG.md
package.json
src/components/DcBoard/index.scss
src/components/DcBoard/index.tsx
src/components/DcBoard/pure-board.tsx
src/components/DcCharts/chart-funnel/default-option.ts
src/components/DcCharts/chart-line/default-option.ts
src/components/DcCharts/chart-line/option.ts
src/components/DcCharts/chart-map/default-option.ts
src/components/DcCharts/chart-pie/default-option.ts
src/components/DcContainer/index.scss
src/types/index.d.ts

style: unified chart style
Fixes #

style: unified chart style

---

CHANGELOG.md
package-lock.json
package.json
src/components/DcCharts/chart-line/option.ts

text map not defined in line options
Fixes #
text map not defined in line options

fix: text map not defined in line options

---

CHANGELOG.md
package.json

docs: update docs to v2.0.12
docs: update docs to v2.0.12
Fixes #

docs: update docs to v2.0.12

---

src/common/form-builder/fields.tsx
src/components/DcCharts/chart-line/option.ts
src/types/index.d.ts
src/utils/version.tsx

feat: fix dataZoom style

---

src/components/DcContainer/index.tsx

feat: remove loading text
Fixes #

feat: remove loading text

---

CHANGELOG.md
package.json
src/components/DcCharts/chart-funnel/option.ts
src/components/DcCharts/chart-line/configurator.tsx
src/components/DcCharts/chart-table/configurator.tsx

1. null display is empty when edit
2. fix that rowEvent is exceed updated
Fixes #

fix: null display is empty when edit
